#!/bin/bash
echo ""
echo "=========================================="
echo "  🛡️  ElasticGuard AI — Ready!"
echo "=========================================="
echo ""
echo "  Quick Start:"
echo "    docker compose up --build"
echo ""
echo "  Then in a new terminal:"
echo "    python setup_elasticsearch.py"
echo "    python iot_simulator.py"
echo "    python anomaly_detector.py"
echo ""
echo "  Dashboard: Port 8000"
echo "  Kibana:    Port 5601"
echo "=========================================="
echo ""
